PaoApp/urls.py
from django.urls import path

from . import views
app_name = 'PaoApp'
urlpatterns = [
    path( '', views.index, name= 'index'),
    path('login/', views.login, name = 'login'),
    path( 'testLogin/', views.testLogin, name = 'testLogin'),
    path( 'register/', views.register, name = 'register'),
    path( 'postRegister/', views.postRegister, name = 'postRegister'),
    path('logout', views.logout, name = 'logout')
]

untitled/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PaoApp.urls'))
]

PaoApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class Usuario( models.Model ):
    nombre_usuario = models.CharField( max_length=200 )
    email = models.CharField(max_length=200)

PaoApp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
import pyrebase
from django.contrib import auth
from .models import Usuario
from django.views.generic.base import TemplateView
config = {
    'apiKey': "AIzaSyAbCiMgh8az4COYBvq038jbrvVGA16oCeo",
    'authDomain': "poliproyecto-6dfb4.firebaseapp.com",
    'databaseURL': "https://poliproyecto-6dfb4.firebaseio.com",
    'projectId': "poliproyecto-6dfb4",
    'storageBucket': "poliproyecto-6dfb4.appspot.com",
    'messagingSenderId': "562557261320",
    'appId': "1:562557261320:web:64f3792e7ca3608c1463bd",
    'measurementId': "G-GED6N0CHKC"
}
firebase = pyrebase.initialize_app(config)

authfb = firebase.auth()

# Create your views here.

@login_required
def index(request):
    return render(request, 'PaoApp/testLogin.html', {})



def login( request ):
    return render( request, 'PaoApp/login.html', { })

def register( request ):
    return render( request, 'PaoApp/register.html', { })

def postRegister(request):
    var_email = request.POST['email']
    password = request.POST['password']
    username = request.POST['username']
    try:
        user = authfb.create_user_with_email_and_password( var_email, password )
        nuevo_usuario = Usuario( nombre_usuario = username, email = var_email )
        nuevo_usuario.save()
    except:
        return render(request, 'PaoApp/register.html', {'error_message' : 'Error al registrar, pruebe con otro email y contraseña de 6 caracteres'})
    return render( request, 'PaoApp/postReg.html', {})

@login_required
def testLogin( request ):
    email = request.POST['email']
    password = request.POST['password']
    try:
        user = authfb.sign_in_with_email_and_password(email, password)
    except:
        message = 'Credenciales invalidas'
        return render( request, 'PaoApp/login.html',{ 'error_message' : message } )
    context = {
        'userFirebaseData': user
    }
    session_id = user['idToken']
    request.session['uid'] = str( session_id )
    return render( request, 'PaoApp/testLogin.html', context)

def logout( request ):
    auth.logout( request )
    return render( request, 'PaoApp/login.html',{})

templates/PaoApp/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Login page</title>
  </head>
  <body>
    <div class="container">
        <h1 class="col-12 text-center">Poliproyectos App</h1>

        Bienvenido!
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/PaoApp/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Login page</title>
  </head>
  <body>
    <div class="container">
        <h1 class="col-12 text-center">Poliproyectos App</h1>
            <div class="row justify-content-center">
                <form class="col-sm-12 col-md-8 col-lg-6 pt-3" method="post" action="{% url 'PaoApp:testLogin' %}">
                    {% csrf_token %}
                    {%  if error_message %}
                        <div class="form-group">
                            <div class=" alert alert-danger">
                                {{ error_message }}
                            </div>
                        </div>
                    {%  endif %}
                    <div class="form-group">
                        <label for="email">Email de usuario</label>
                        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="form-group">
                        <label for="password">Contraseña</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
                    <button class="btn btn-primary mt-3"> Registrarse</button>
                </form>
            </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/PaoApp/postReg.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Landing page</title>
  </head>
  <body>
    <div class="nav-bar bg-primary p-4 mb-3">
        <h1 class="text-white text-center">Poliproyecto</h1>
    </div>
    <div class="container">
        <div>

            <h3>Usuario creado con exito!</h3>

            <h3><a href="{% url 'PaoApp:login' %}">Acceder</a></h3>
            <h3><a href="{% url 'PaoApp:register' %}">Registrar nuevo usuario</a></h3>
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/PaoApp/register.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Register page</title>
  </head>
  <body>
    <div class="container">
        <h1 class="col-12 text-center">Poliproyectos App</h1>
            <div class="row justify-content-center mt-3">
                <form class="col-sm-12 col-md-8 col-lg-6 pt-3 needs-validation" novalidate method="post" action="{% url 'PaoApp:postRegister' %}" onsubmit="e=>checkPass(e)">
                    {% csrf_token %}
                    {%  if error_message %}
                        <div class="form-group">
                            <div class=" alert alert-danger">
                                {{ error_message }}
                            </div>
                        </div>
                    {%  endif %}
                    <div class="form-group">
                        <label for="username">Nombre de usuario</label>
                        <input type="text" class="form-control" id="username" aria-describedby="emailHelp" name="username">
                    </div>
                    <div class="form-group">
                        <label for="email">Email de usuario</label>
                        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Contraseña</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                        <div class="invalid-feedback">
                            La contrasenha debe tener al menos 6 caracteres
                         </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mb-3" id="registerButton">Registrarse</button>

                </form>
            </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-    3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    -->
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
            'use strict';
            window.addEventListener('load', function() {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var form = document.querySelector('.needs-validation');
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
            }, false);
        })();
    </script>
  </body>
</html>

templates/PaoApp/testLogin.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Landing page</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    </li>
                </ul>
                <div class="form-inline my-2 my-lg-0">
                    <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'PaoApp:logout' %}">Cerrar sesion</a>
                </div>
            </div>
        </nav>
    <div class="container">
        <div class="row">
            <h1 class="col-12 mb-3">Bienvenido
            {%  if userFirebaseData.displayName %}
                {{  userFirebaseData.displayName }}
            {% elif userFirebaseData.email %}
                {{  userFirebaseData.email }}
            {% endif %}
            !</h1>

            Easy SSO
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>